"""Masquelier 2008 on NEST GPU, for a wall-time comparison with SuperNeuroABM.

Builds the same experiment as
``/home/xxz/ns-applications/duplicates/masquelier_2008/run_experiment_hg.py``:
2000 external afferents feeding one output neuron through 2000 plastic synapses,
driven by the *identical* spike trains (generated by that experiment's own
``experiment_utils``), for one 10 s chunk at dt = 0.1 ms.

Model equivalence is approximate and deliberately so. SuperNeuroABM uses the
Hathway-Goodman 3-variable LIF with exact linear integration and a
single-exponential current synapse; NEST GPU gets ``iaf_psc_exp`` with the same
membrane and synaptic time constants and a nearest-neighbour ``stdp`` synapse
group with the same trace time constants and bounds. This measures the cost of
delivering ~1.2M input spikes and running 100,000 plastic steps, not numerical
agreement. Spike counts will differ.
"""

import argparse
import sys
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
MASQ_DIR = Path("/home/xxz/ns-applications/duplicates/masquelier_2008")
sys.path.insert(0, str(MASQ_DIR))

import numpy as np

import bench_common as bc

# masquelier_config.yaml, masq_hg_lif_soma.py and exp_pair_wise_stdp_bounded_nn.py
TAU_M_MS = 10.0        # taum
TAU_SYN_MS = 2.5       # tau_fall of the single-exp synapse
T_REF_MS = 1.0         # tref
TAU_PRE_MS = 16.8      # STDP potentiation time constant
TAU_POST_MS = 33.7     # STDP depression time constant
A_PRE = 2 ** -5        # a_exp_pre
A_POST_RATIO = 0.85    # a_exp_post / a_exp_pre
W_INIT = 0.475
W_MAX = 1.0


def build_parser():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--seconds", type=float, default=10.0)
    p.add_argument("--dt-ms", type=float, default=0.1)
    p.add_argument("--afferents", type=int, default=2000)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--weight-pa", type=float, default=200.0,
                   help="Peak synaptic current for w=1; scales the whole network.")
    p.add_argument("--csv", default=str(SCRIPT_DIR / "results" / "masquelier.csv"))
    return p


def generate_trains(args, log):
    """Spike trains from the SuperNeuroABM experiment's own generator."""
    import experiment_utils as eu

    n_ticks_gen = int(args.seconds / eu.DT)         # generator runs at 1 ms
    rng = np.random.default_rng(args.seed)
    t0 = time.time()
    rates = eu.generate_rate_profiles(args.afferents, n_ticks_gen, rng)
    trains = eu.generate_poisson_spikes(rates, rng)
    pattern = eu.generate_pattern(eu.N_PATTERN, eu.PATTERN_DURATION, rng)
    trains, _ = eu.embed_pattern(trains, pattern, n_ticks_gen, rng)
    log.add("generate_spikes", time.time() - t0)
    # Generator ticks are 1 ms; the simulation runs at dt_ms.
    return [np.asarray(t, dtype=np.float64) * (eu.DT * 1000.0) for t in trains]


def run(args):
    import nestgpu as ngpu

    log = bc.PhaseLog("nestgpu", "masquelier", args.afferents, 1,
                      synapses=args.afferents)
    t_pipeline = time.time()

    trains = generate_trains(args, log)
    n_spikes = sum(len(t) for t in trains)

    ngpu.SetKernelStatus("min_allowed_delay", max(args.dt_ms, 0.1))
    ngpu.SetKernelStatus("time_resolution", args.dt_ms)
    ngpu.SetKernelStatus("rnd_seed", args.seed)
    ngpu.SetKernelStatus("verbosity_level", 1)

    # ---- create ----
    t0 = time.time()
    gens = ngpu.Create("spike_generator", args.afferents)
    soma = ngpu.Create("iaf_psc_exp", 1)
    ngpu.SetStatus(soma, {
        "tau_m": TAU_M_MS, "C_m": 250.0, "E_L": 0.0, "I_e": 0.0,
        "Theta_rel": 20.0, "V_reset_rel": 0.0,
        "tau_ex": TAU_SYN_MS, "tau_in": TAU_SYN_MS, "t_ref": T_REF_MS,
    })
    log.add("create", time.time() - t0)

    # ---- load the spike trains onto the generators ----
    t0 = time.time()
    for i in range(args.afferents):
        if len(trains[i]):
            ngpu.SetStatus(gens[i:i + 1], {"spike_times": trains[i].tolist()})
    log.add("load_spike_trains", time.time() - t0)

    # ---- connect, with plasticity ----
    t0 = time.time()
    syn_group = ngpu.CreateSynGroup("stdp", {
        "tau_plus": TAU_PRE_MS, "tau_minus": TAU_POST_MS,
        "lambda": A_PRE, "alpha": A_POST_RATIO,
        "mu_plus": 0.0, "mu_minus": 0.0,   # additive rule, as in the SNA version
        "Wmax": W_MAX * args.weight_pa,
    })
    ngpu.Connect(gens, soma, {"rule": "all_to_all"},
                 {"weight": W_INIT * args.weight_pa, "delay": max(args.dt_ms, 0.1),
                  "synapse_group": syn_group})
    log.add("connect", time.time() - t0)

    try:
        ngpu.ActivateSpikeCount(soma)
    except Exception as err:
        print(f"  (spike count unavailable: {err})")

    t0 = time.time()
    ngpu.Calibrate()
    log.add("calibrate", time.time() - t0)

    # ---- simulate ----
    t0 = time.time()
    ngpu.Simulate(args.seconds * 1000.0)
    log.add("simulate", time.time() - t0)

    log.add("total", time.time() - t_pipeline)

    n_out = float("nan")
    try:
        c = ngpu.GetStatus(soma, "spike_count")
        n_out = float(c[0][0]) if isinstance(c[0], (list, tuple)) else float(c[0])
    except Exception:
        pass

    bc.print_table(log.rows, f"NEST GPU Masquelier  {args.afferents} afferents, "
                             f"{args.seconds:g}s @ dt={args.dt_ms}ms")
    print(f"\n  input spikes delivered: {n_spikes:,}")
    print(f"  output spikes: {n_out}")
    log.write(args.csv)
    print(f"  wrote {args.csv}")


if __name__ == "__main__":
    run(build_parser().parse_args())
