soma:
  lif_soma:
    digits_input_config:
      hyperparameters:
        C: 10e-9
        R: 1e6
        vthr: -45
        tref: 5e-3
        vrest: -60
        vreset: -60
        tref_allows_integration: 0
        I_in: 0
        scaling_factor: 1e-5
      internal_state:
        v: -60.0
        tcount: 0.0
        tlast: -1.0
    digits_output_config:
      hyperparameters:
        C: 10e-9
        R: 1e6
        vthr: -45
        tref: 5e-3
        vrest: -60
        vreset: -60
        tref_allows_integration: 0
        I_in: 0
        scaling_factor: 1e-5
      internal_state:
        v: -60.0
        tcount: 0.0
        tlast: -1.0

synapse:
  single_exp_synapse:
    digits_input_synapse_config:
      hyperparameters:
        weight: 20.0
        synaptic_delay: 1.0
        scale: 1.0
        tau_fall: 3e-3
        tau_rise: 0
      internal_state:
        I_synapse: 0.0

    digits_learning_synapse_config:
      hyperparameters:
        weight: 0.3
        synaptic_delay: 1.0
        scale: 1.0
        tau_fall: 3e-3
        tau_rise: 0
      internal_state:
        I_synapse: 0.0

    digits_target_synapse_config:
      hyperparameters:
        weight: 20.0
        synaptic_delay: 1.0
        scale: 1.0
        tau_fall: 1e-3
        tau_rise: 0
      internal_state:
        I_synapse: 0.0

    digits_learning_synapse_config_memristive:
      hyperparameters:
        weight: 0.5
        synaptic_delay: 1.0
        scale: 1.0
        tau_fall: 1e-2
        tau_rise: 0
      internal_state:
        I_synapse: 0.0

learning_rule:
  exp_pair_wise_stdp_bounded:
    digits_bounded:
      learning_hyperparameters:
        stdp_type: 2.0
        tau_pre_stdp: 10e-3
        tau_post_stdp: 10e-3
        a_exp_pre: 0.1
        a_exp_post: 0.35
        stdp_history_length: 100
        wmin: 0.0
        wmax: 1.0
      internal_learning_state:
        pre_trace: 0
        post_trace: 0
        dW: 0

  memristive_exp_pair_wise_stdp:
    digits_memristive:
      learning_hyperparameters:
        stdp_type: 3.0
        tau_pre_stdp: 10e-3
        tau_post_stdp: 10e-3
        a_exp_pre: 0.5
        a_exp_post: 1.0
        stdp_history_length: 100
        wmin: 0.0
        wmax: 1.0
      internal_learning_state:
        pre_trace: 0
        post_trace: 0
        dW: 0
